Accountancy_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('bank/', include('bank.urls')),
    path('scoreboard/', include('scoreboard.urls')),
    path('market/', include('market.urls'))
]

bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'
urlpatterns = [
    path('bank_home/', views.bank_home, name='bank_home'),
    path('get_team_info/', views.get_team_info, name='get_team_info'),
    path('buying_questions/', views.buying_questions, name='buying_questions'),
    path('trading_questions/', views.trading_questions, name='trading_questions'),
    path('receive_award/', views.receive_award, name='receive_award'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    # navbar urls
    path("apply_inflation_interest/", views.apply_inflation_interest, name="apply_inflation_interest"),
    path("inflation_apply/", views.apply_inflation_view, name="apply_inflation"),
    path("interest_apply/", views.apply_interest_view, name="apply_interest"),
    path("reset_inflation/", views.reset_inflation, name="reset_inflation"),

    # login urls
    path('admin_or_user/', views.admin_or_user, name='admin_or_user'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('banker_login/', views.banker_login, name='banker_login'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
    path("banker-logout/", views.banker_logout, name="banker_logout"),
    
    path('entry_page/', views.Entry_page, name='Entry_page'),
    path('setting/', views.setting, name='setting'),
    path('competition/', views.Home, name='home'),
    
    path('step1_base/', views.setup_step1, name='setup_step1'),
    path('step2_questions/', views.setup_step2, name='setup_step2'),
    path('step3_items/', views.setup_step3, name='setup_step3'),
    path('step4_inflation/', views.setup_step4, name='setup_step4'),
]

market/urls.py
from django.urls import path
from . import views

app_name = 'market'
urlpatterns = [
    path('get_team_item_info/', views.get_team_item_info, name='get_team_item_info'),
    path('dealing_items/', views.dealing_items, name='dealing_items'),
]

bank/models.py
from django.db import models

class Question(models.Model):
    LEVEL_CHOICE = [
        ('easy' , 'آسان'),
        ('medium' , 'متوسط'),
        ('hard' , 'سخت')
        ]
    
    level = models.CharField(max_length=10, choices=LEVEL_CHOICE, verbose_name='سطح سوال')
    buy_price = models.DecimalField(max_digits=10,decimal_places=0, verbose_name='قیمت خرید')
    sell_price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='قیمت فروش')
    stock = models.PositiveIntegerField(default=0, verbose_name='تعداد در بانک')
    
    class Meta:
        verbose_name = 'سوال'
        verbose_name_plural = 'سوال‌ها'
        ordering = ['level']
        
    def __str__(self):
        return f"{self.get_level_display()} - خرید: {self.buy_price} / فروش: {self.sell_price} (موجودی: {self.stock})"

        

bank/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.db import transaction
from decimal import Decimal

from .models import Question
from accounts.models import Team


def bank_home(request):
    return render(request, 'bank/bank_home.html')

def get_team_info(request):
    team_id = request.GET.get('team_id')
    try:
        team = Team.objects.get(id=team_id)
        data = {
            'name': team.group_name,
            'unsolved': team.unsolved_questions,
            'solved': team.solved_questions,
        }
        return JsonResponse(data)
    except Team.DoesNotExist:
        return JsonResponse({'error': 'تیمی با این شناسه وجود ندارد'})

@transaction.atomic
def buying_questions(request):
    teams = Team.objects.all()
    questions = Question.objects.all()
    
    if request.method == 'POST':
        team_id = request.POST.get('team')
        level = request.POST.get('level')
        
        team = Team.objects.get(id=team_id)
        team_balance = team.bank_balance
        question = Question.objects.get(level=level)
        price = question.buy_price
        

        if team_balance < price:
            messages.error(
                request,
                'موجودی گروه برای خرید سوال کافی نیست',
                extra_tags='alert-danger'
            )
            return redirect('bank:buying_questions')
        
        if question.stock <= 0:
            messages.error(
                request,
                'سؤالی در بانک موجود نیست',
                extra_tags='alert-danger'
            )
            return redirect('bank:buying_questions')
        

        # Apply changes
        team.bank_balance -= price
        team.unsolved_questions += 1
        team.save()

        question.stock -= 1
        question.save()

        messages.success(
            request,
            f" گروه {team.team_number} یک سؤال {question.get_level_display()} خرید.",
            extra_tags='alert-success'
        )
        return redirect('bank:buying_questions')
    
    return render(request, 'bank/buying_questions.html', {
        'teams': teams,
        'questions': questions,
    })
    

@transaction.atomic
def trading_questions(request):
    teams = Team.objects.all()
    questions = Question.objects.all()
    
    if request.method == 'POST':
        seller_team_id = request.POST.get('seller_team')
        recipient_team_id = request.POST.get('recipient_team')
        if seller_team_id == recipient_team_id:
            messages.error(
                request,
                f'گروه خریدار و فروشنده یکسان است',
                extra_tags='alert-danger'
            )
            return redirect('bank:trading_questions')
            
        consensual_price = Decimal(request.POST.get('consensual_price') or 0)

        seller_team = Team.objects.get(id=seller_team_id)
        recipient_team = Team.objects.get(id=recipient_team_id)
        recipient_balance = recipient_team.bank_balance
        
        if seller_team.unsolved_questions <= 0:
            messages.error(
                request,
                f'سؤال حل نشده‌ای در بانک گروه {recipient_team.team_number} موجود نیست.',
                extra_tags='alert-danger'
            )
            return redirect('bank:trading_questions')
        
        if recipient_balance < consensual_price:
            messages.error(
                request,
                'موجودی گروه خریدار برای خرید سوال کافی نیست',
                extra_tags='alert-danger'
            )
            return redirect('bank:trading_questions')
         
        
        recipient_team.bank_balance -= consensual_price
        recipient_team.unsolved_questions += 1
        
        seller_team.bank_balance += consensual_price
        seller_team.unsolved_questions -= 1
        
        recipient_team.save()
        seller_team.save()
        
        messages.success(
            request,
            f"گروه {seller_team.team_number} یک سؤال با قیمت {consensual_price} به گروه {recipient_team.team_number} فروخت.",
            extra_tags='alert-success'
        )
        return redirect('bank:trading_questions')
    
    return render(request, 'bank/trading_questions.html', {
        'teams': teams,
        'questions': questions,
    })
    

@transaction.atomic
def receive_award(request):
    teams = Team.objects.all()
    questions = Question.objects.all()
    
    if request.method == 'POST':
        team_id = request.POST.get('team')
        level = request.POST.get('level')
        
        team = Team.objects.get(id=team_id)
        question = Question.objects.get(level=level)
        price = question.sell_price
        
        if team.unsolved_questions == 0:
            messages.error(
                request,
                f"گروه {team.team_number} سوال حل نشده‌ای ندارد.",
                extra_tags='alert-danger'
            )
            return redirect('bank:receive_award')
            
        team.bank_balance += price
        team.solved_questions += 1
        team.unsolved_questions -= 1
        team.save()
        
        messages.success(
            request,
            f" گروه {team.team_number} جایزه یک سؤال {question.get_level_display()} را دریافت کرد.",
            extra_tags='alert-success'
        )
        return redirect('bank:receive_award')
        
    return render(request, 'bank/receive_award.html', {
        'teams': teams,
        'questions': questions,
    })

bank/templates/bank/bank_home.html
{% extends "base.html" %}
{% load static %}


{% block css_files %}
    <link rel="stylesheet" href="{% static "bank/bank_home.css" %}">
{% endblock css_files %}

{% block page_title %}صفحه اصلی بانک{% endblock page_title %}

{% block page_content %}

    <div class="container text-center mt-5">
    <h1 class="mb-4"> بانک </h1>

    <div class="d-grid gap-3 col-6 mx-auto">
        <a href="{% url 'bank:buying_questions' %}" class="btn btn-primary btn-lg"> خرید سوال</a>
        <a href="{% url 'bank:receive_award' %}" class="btn btn-warning btn-lg"> دریافت جایزه سوال</a>
        <a href="{% url 'bank:trading_questions' %}" class="btn btn-danger btn-lg"> تبادل سوال بین گروه ها</a>
        <a href="{% url 'market:dealing_items' %}" class="btn btn-info btn-lg">خرید و فروش کالا</a>
        <a href="{% url 'core:home' %}" class="btn btn-dark btn-lg">بازگشت</a>
        
    </div>
    </div>


{% endblock page_content %}

{% block page_scripts %}{% endblock page_scripts %}

bank/templates/bank/buying_questions.html
{% extends "base.html" %}
{% load static %}


{% block css_files %}
    <link rel="stylesheet" href="{% static "core/buying_questions.css" %}">
{% endblock css_files %}

{% block page_title %}خریدن سوال{% endblock page_title %}

{% block page_content %}

<div class="container text-center">
 <div class="container col-md-5">

  <!-- Messages Section -->
  <div class="message-container mb-3" style="min-height: 60px;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  </div>



  <h2 class="mb-4 text-center"> خرید سؤال از بانک</h2>

  <form method="POST" id="buyForm">
    {% csrf_token %}
    <div class="mb-3">
      <label>انتخاب گروه:</label>
      <select name="team" id="teamSelect" class="form-select" required>
        <option value="">انتخاب گروه</option>
        {% for t in teams %}
          <option value="{{ t.id }}">{{ t.team_number }} - {{ t.group_name }}</option>
        {% endfor %}
      </select>
    </div>

    <!-- showing team information-->
    <div id="teamInfo" class="alert alert-secondary" style="display:none;">
      <strong id="teamName"></strong><br>
      حل‌نشده‌ها: <span id="unsolvedCount"></span> |
      حل‌شده‌ها: <span id="solvedCount"></span>
    </div>

    <div class="mb-3">
      <label>سطح سؤال:</label>
      <select name="level" class="form-select" required>
        <option value="">انتخاب سطح</option>
        {% for q in questions %}
          <option value="{{ q.level }}">{{ q.get_level_display }} ({{ q.stock }} عدد باقی مانده)</option>
        {% endfor %}
      </select>
    </div>

    <div class="text-center mt-3">
      <button id="applyButton" type="submit" class="btn btn-primary btn-lg">خرید سؤال</button>
      <a href="{% url 'bank:bank_home' %}" class="btn btn-secondary btn-lg">بازگشت</a>
    </div>
  </form>

</div>

{% endblock page_content %}


{% block page_scripts %}
<script>


document.addEventListener('DOMContentLoaded', function() {

  // Showing group info after choosing it
  document.getElementById('teamSelect').addEventListener('change', function() {
    const teamId = this.value;
    const infoBox = document.getElementById('teamInfo');

  if (!teamId) {
    infoBox.style.display = 'none';
    return;
  }

  fetch(`/bank/get_team_info/?team_id=${teamId}`)
    .then(res => res.json())
    .then(data => {
      if (data.error) {
        infoBox.style.display = 'none';
      } else {
        document.getElementById('teamName').textContent = data.name;
        document.getElementById('unsolvedCount').textContent = data.unsolved;
        document.getElementById('solvedCount').textContent = data.solved;
        infoBox.style.display = 'block';
      }
    })
    .catch(err => console.error("خطا در گرفتن اطلاعات تیم:", err));
});

      // Fading alerts
      const alerts = document.querySelectorAll('.alert:not(.alert-success):not(.alert-secondary)');

      alerts.forEach(alert => {
        setTimeout(() => {
          alert.style.transition = "opacity 1s";
          alert.style.opacity = "0";

          setTimeout(() => {
            alert.remove();
          }, 1000);
        }, 3000);
      });


      // If the operation was successful, the page reloads after 2 seconds
      const successAlert = document.querySelector('.alert-success');
      if (successAlert) {
          setTimeout(() => {
            window.location.reload();
          }, 2700);
      }
  });
</script>
{% endblock page_scripts %}

bank/templates/bank/receive_award.html
{% extends "base.html" %}
{% load static %}


{% block css_files %}
    <link rel="stylesheet" href="{% static "bank/receive_award.css" %}">
{% endblock css_files %}

{% block page_title %}دریافت جایزه سوال{% endblock page_title %}

{% block page_content %}

<div class="container text-center">
 <div class="container col-md-5">

  <!-- Messages Section -->
  <div class="message-container mb-3" style="min-height: 60px;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  </div>

  <h2 class="mb-4 text-center"> دریافت جایزه سوال </h2>

  <form method="POST" id="buyForm">
    {% csrf_token %}
    <div class="mb-3">
      <label>انتخاب گروه:</label>
      <select name="team" id="teamSelect" class="form-select" required>
        <option value="">انتخاب گروه</option>
        {% for t in teams %}
          <option value="{{ t.id }}">{{ t.team_number }} - {{ t.group_name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label>سطح سؤال:</label>
      <select name="level" class="form-select" required>
        <option value="">انتخاب سطح</option>
        {% for q in questions %}
          <option value="{{ q.level }}">{{ q.get_level_display }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="text-center mt-3">
      <button type="submit" class="btn btn-primary btn-lg">دریافت جایزه</button>
      <a href="{% url 'bank:bank_home' %}" class="btn btn-secondary btn-lg">بازگشت</a>
    </div>
  </form>
</div>

{% endblock page_content %}


{% block page_scripts %}
<script>

document.addEventListener('DOMContentLoaded', function() {

    // Fading alerts
    const alerts = document.querySelectorAll('.alert:not(.alert-success)');

    alerts.forEach(alert => {
      setTimeout(() => {
        alert.style.transition = "opacity 1s";
        alert.style.opacity = "0";

        setTimeout(() => {
          alert.remove();
        }, 1000);
      }, 3000);
    });

    // If the operation was successful, the page reloads after 2 seconds
    const successAlert = document.querySelector('.alert-success');
    if (successAlert) {
        setTimeout(() => {
          window.location.reload();
        }, 2700);
    }
});

</script>
{% endblock page_scripts %}

bank/templates/bank/trading_questions.html
{% extends "base.html" %}
{% load static %}


{% block css_files %}
    <link rel="stylesheet" href="{% static "bank/trading_questions.css" %}">
{% endblock css_files %}

{% block page_title %}تبادل سوال{% endblock page_title %}

{% block page_content %}

<div class="container text-center">
 <div class="container col-md-5">

  <!-- Messages Section -->
  <div class="message-container mb-3" style="min-height: 60px;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
  </div>



  <h2 class="mb-4 text-center">تبادل سوال بین گروه‌ها</h2>

  <form method="POST" id="buyForm">
    {% csrf_token %}
    <div class="mb-3">
      <label> انتخاب گروه فروشنده:</label>
      <select name="seller_team" id="sellerSelect" class="form-select" required>
        <option value="">انتخاب گروه فروشنده</option>
        {% for t in teams %}
          <option value="{{ t.id }}">{{ t.team_number }} - {{ t.group_name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label>انتخاب گروه خریدار:</label>
      <select name="recipient_team" id="buyerSelect" class="form-select" required>
        <option value="">انتخاب گروه خریدار</option>
        {% for t in teams %}
          <option value="{{ t.id }}">{{ t.team_number }} - {{ t.group_name }}</option>
        {% endfor %}
      </select>
    </div>

    <div id="consensual_price" class="mb-3">
      <label>قیمت توافقی سوال:</label>
      <input type="number" name="consensual_price" class="form-control" value="0">
    </div>

    <div class="text-center mt-3">
      <button type="submit" class="btn btn-primary btn-lg">تبادل سؤال</button>
      <a href="{% url 'bank:bank_home' %}" class="btn btn-secondary btn-lg">بازگشت</a>
    </div>
  </form>
</div>

{% endblock page_content %}


{% block page_scripts %}
<script>

document.addEventListener('DOMContentLoaded', function() {

      // Fading alerts
      const alerts = document.querySelectorAll('.alert:not(.alert-success)');

      alerts.forEach(alert => {
        setTimeout(() => {
          alert.style.transition = "opacity 1s";
          alert.style.opacity = "0";

          setTimeout(() => {
            alert.remove();
          }, 1000);
        }, 3000);
      });

      // If the operation was successful, the page reloads after 2 seconds
      const successAlert = document.querySelector('.alert-success');
      if (successAlert) {
          setTimeout(() => {
            window.location.reload();
          }, 2700);
      }
  });

</script>
{% endblock page_scripts %}